config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/dashboard", to: "pages#dashboard"
  get "/admin", to: "pages#admin"
  post "/admin", to: "pages#send_reminder", as: :send_reminders

  resources :user_subscriptions, only: [ :show, :new, :create, :edit, :update, :destroy] do
    resources :reminders, only: [ :index, :show, :new, :create, :edit]
  end
  resources :reminders, only: [:destroy, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/billing_plan.rb
class BillingPlan < ApplicationRecord
  has_many :user_subscriptions

  PLANS = {
    "Weekly": 1.week,
    "Monthly": 1.month,
    "3 months": 3.month,
    "12 months": 1.year,
    "24 months": 2.year
  }
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/reminder.rb
class Reminder < ApplicationRecord
  belongs_to :user_subscription
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :category
  
  has_one_attached :logo
  has_many :reminders
end

app/models/user.rb
class User < ApplicationRecord
  # after_create :send_welcome_email
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :user_subscriptions

  validates :first_name, presence: true, length: { maximum: 10 }
  validates :last_name, presence: true, length: { maximum: 10 }

  private

  def send_welcome_email
    UserMailer.with(user: self).welcome.deliver_now
  end
end

app/models/user_subscription.rb
class UserSubscription < ApplicationRecord
  after_create :async_update
  attr_accessor :add_reminder #Used for simple_form (not on schema)
  belongs_to :user
  belongs_to :subscription
  has_many :reminders, dependent: :destroy
  accepts_nested_attributes_for :reminders, reject_if: :all_blank
  belongs_to :billing_plan
  validates :payment_date, presence: true
  validates :cost, presence: true

  private

  def async_update
    UpdatePaymentJob.perform_later(self) unless ["Free trial", "Lifetime"].include?(self.billing_plan.name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def default_url_options
    { host: ENV["scriber.uk"] || "localhost:3000" }
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/pages_controller.rb
require 'date'

class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def admin
  end

  def send_reminder
    @reminders = Reminder.where(date: Date.today)
    @reminders.each do |reminder|
      @user = reminder.user_subscription.user
      @reminder = reminder
      ReminderMailer.with(user: @user, reminder: @reminder).reminder.deliver_now
    end
    redirect_to admin_path
  end

  def dashboard
    @user = current_user
    @user_subscriptions = @user.user_subscriptions

    user_reminders(@user_subscriptions)

    subscriptions_current_month(@user_subscriptions)

    subscription_search(@user_subscriptions)
  end

  private

  def user_reminders(user_subscriptions)
    @user_reminders = []
    user_reminder_dates = []
    user_subscriptions.each do |subscription|
      subscription.reminders.each do |reminder|
        @user_reminders << reminder
        user_reminder_dates << reminder.date
      end
      @date_today_count = 0;
      @date_match = false;
      user_reminder_dates.each do |date|
        @date_match = date == Date.today ? true : false
        date == Date.today ? @date_today_count += 1 : false
      end
    end
  end

  def subscriptions_current_month(user_subscriptions)
    @subscriptions_current_month = []
    user_subscriptions.each do |subscription|
      if subscription.payment_date.mon == Date.today.month
        @subscriptions_current_month << subscription
      end
    end

    current_month_costs = []
    @subscriptions_current_month.each do |subscription|
        current_month_costs << subscription.cost
    end
    @total_cost = current_month_costs.sum
  end

  def subscription_search(user_subscriptions)
    if params[:query].present?
      sql_query = " \
        subscriptions.name ILIKE :query \
      "
      @search_results = UserSubscription.joins(:subscription).where(sql_query, query: "%#{params[:query]}%")
    else
      @search_results = user_subscriptions
    end
  end

end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_action :set_reminder, only: [:edit, :update, :destroy]

  def index
    @reminders = Reminder.all
    @user_subscription = UserSubscription.find(params[:user_subscription_id])
  end

  def new
    @reminder = Reminder.new
    @user_subscription = UserSubscription.find(params[:user_subscription_id])
  end

  def create
    @reminder = Reminder.new(reminder_params)
    @user_subscription = UserSubscription.find(params[:user_subscription_id])
    @reminder.user_subscription = @user_subscription
    unless @reminder.details == ""
      @reminder.save
      redirect_to user_subscription_path(@user_subscription)
    end
  end

  def edit
  end

  def update
    @reminder.update(reminder_params)
    redirect_to user_subscription_path(@reminder.user_subscription)
  end

  def destroy
    @reminder.destroy
    redirect_to user_subscription_path(@reminder.user_subscription)
  end

  private

  def set_reminder
    @reminder = Reminder.find(params[:id])
  end

  def reminder_params
    params.require(:reminder).permit(:date, :details)
  end
end

app/controllers/user_subscriptions_controller.rb
class UserSubscriptionsController < ApplicationController
  before_action :set_user_subscription, only: [:show, :edit, :update, :destroy]

  def new
    @user_subscription = UserSubscription.new
    @user_subscription.reminders.build
  end

  def show
    if @user_subscription.end_date.nil?
      @date = nil
    else
    @date = @user_subscription.end_date - @user_subscription.start_date
  end

  end

  def create
    @user_subscription = UserSubscription.new(user_subscription_params)
    @user_subscription.user = current_user

    if @user_subscription.save
      UpdatePaymentJob.set(wait_until: @user_subscription.payment_date.noon).perform_later(@user_subscription)
     redirect_to dashboard_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @user_subscription.update(user_subscription_params)
    redirect_to user_subscription_path(@user_subscription)
  end

  def destroy
    @user_subscription.destroy
    redirect_to dashboard_path
  end

  private

  def set_user_subscription
    @user_subscription = UserSubscription.find(params[:id])
  end

  def user_subscription_params
    params.require(:user_subscription).permit(:start_date, :end_date, :payment_date, :cost,
    :billing_plan_id, :user_id, :subscription_id, :add_reminder, reminders_attributes: [:date, :details])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
# app/helpers/meta_tags_helper.rb

module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag %>

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="page-container">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
      <div class="main-container">
        <%= yield %>
      </div>
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/pages/_dash_pie.html.erb
<% category_hash={
  Entertainment: 0,
  Cloudstorage: 0,
  Software: 0,
  Foodanddrink: 0,
  Beauty: 0,
  Phone: 0,
  Health: 0,
  Utilities: 0
} %>
<% @user_subscriptions.each do |sub| %>
  <%case sub.subscription.category.id %>
<%when 1 %>
 <% category_hash[:Entertainment] += 1 %>
 <%when 2 %>
 <% category_hash[:Cloudstorage] += 1 %>
 <%when 3 %>
 <% category_hash[:Software] += 1 %>
 <%when 4 %>
 <% category_hash[:Foodanddrink] += 1 %>
 <%when 5 %>
 <% category_hash[:Beauty] += 1 %>
 <%when 6 %>
 <% category_hash[:Phone] += 1 %>
 <%when 7 %>
 <% category_hash[:Health] += 1 %>
 <%when 8 %>
 <% category_hash[:Utilities] += 1 %>
<% else%>
  <% "" %>
<% end %>
<% end  %>


<section class="pi-chart">
    <div class="pieID pie">

    </div>
    <ul class="pieID legend">
      <li>
        <em>Entertainment</em>
        <span><%= category_hash[:Entertainment]%></span>
      </li>
      <li>
        <em>Cloud storage</em>
        <span><%= category_hash[:Cloudstorage] %></span>
      </li>
      <li>
        <em>Software</em>
        <span><%= category_hash[:Software]%></span>
      </li>
      <li>
        <em>Food and drink</em>
        <span><%= category_hash[:Foodanddrink] %></span>
      </li>
      <li>
        <em>Beauty</em>
        <span><%= category_hash[:Beauty]%></span>
      </li>

      <li>
        <em>Phone</em>
        <span><%= category_hash[:Phone]%></span>
      </li>

      <li>
        <em>Health</em>
        <span><%= category_hash[:Health]%></span>
      </li>

      <li>
        <em>Utilities</em>
        <span><%= category_hash[:Utilities]%></span>
      </li>
    </ul>
  </section>
  <section>

app/views/pages/_dash_tab_all.html.erb
<div class="row justify-content-center">
  <div class="col-12 col-lg-8">
    <h2 class="text-center mb-3">All subscriptions</h2>
    <%= form_tag dashboard_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control search-input",
        placeholder: "Search"
      %>
    <% end %>

    <%= link_to new_user_subscription_path, class: "btn" do %>
      Add Subscription <i class="far fa-calendar-plus"></i>
    <% end %>

    <div class="sub-results">
      <% search_results.each do |user_subscription| %>
        <div class="subscription-item-dash" style="border: 1px solid <%= user_subscription.subscription.category.colour %>; border-left: 8px solid <%= user_subscription.subscription.category.colour %>;">
          
          <div class="sub-item-overlay">
            <%=link_to user_subscription_path(user_subscription) do %>
              <i class="far fa-edit"></i>
            <% end %>

            <%=link_to user_subscription_reminders_path(user_subscription) do %>
            <i class="far fa-bell"></i>
            <% end %>
          </div>

          <% if user_subscription.subscription.logo_url.nil? %>
            <div class="sub-logo-dash">
              <img src="https://res.cloudinary.com/dkyy/image/upload/v1598968617/Logos/scriber_pe33n6.png" alt="" style="width: 70px; height: 70px;">
            </div>
          <% else %>
            <div class="sub-logo-dash">
              <img src="<%= user_subscription.subscription.logo_url %>" alt="" style="width: 70px; height: 70px;">
            </div>
          <% end %>
          
          <div class="sub-info-dash">
            <h3 class="sub-name-dash margin-sm"><%= user_subscription.subscription.name %></h3>
            <p class='sub-next-payment-dash margin-sm'>Next payment: <%= user_subscription.payment_date %></p>
          </div>

          <div class="sub-reg-cost-dash"><h3>£<%= number_with_precision(user_subscription.cost, precision: 2) %></h3></div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/_dash_tab_current.html.erb
<div class="main-dash">
  <div class="subscription-add text-right">
    <%= link_to new_user_subscription_path, class: "btn btn-primary" do %>
      Add subscription <i class="fas fa-plus"></i>
    <% end %>
  </div>

  <div class="row justify-content-around">
    <div class="col-12 col-lg-6">

      <h2 class="mb-3">Current subscriptions</h2>


      <div class="sub-results">
        <% user_subscriptions.each do |user_subscription| %>
          <div class="subscription-item-dash" style="border: 2px solid <%= user_subscription.subscription.category.colour %>; border-left: 8px solid <%= user_subscription.subscription.category.colour %>;">
            <div class="sub-item-overlay">
              <%=link_to user_subscription_path(user_subscription) do %>
                <i class="fas fa-info"></i>
              <% end %>

              <%= link_to edit_user_subscription_path(user_subscription) do %>
                <i class="fas fa-edit"></i>
              <% end %>

              <%= link_to user_subscription_path(user_subscription), method: :delete, data: { confirm: "Are you sure you want to delete this subscription?" } do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            </div>

            <% if user_subscription.subscription.logo_url.nil? %>
              <img src="https://res.cloudinary.com/dkyy/image/upload/v1598968617/Logos/scriber_pe33n6.png" alt="">
            <% else %>
              <img src="<%= user_subscription.subscription.logo_url %>" alt="">
            <% end %>

            <div class="sub-info-dash">
              <h3 class="sub-name-dash"><%= user_subscription.subscription.name %></h3>
              <p class='sub-next-payment-dash'>Next payment: <%= user_subscription.payment_date %></p>
            </div>

            <div class="sub-reg-cost-dash">
              <h3>£<%= number_with_precision(user_subscription.cost, precision: 2) %></h3>
              <% if user_subscription.reminders.length > 0 %>
                <p class="m-0" id="setAlert">🔔</p>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div class="col-12 col-lg-6">
      <h2 class="mb-3">This month</h2>
      <div class="sub-results">
        <% subscriptions_current_month.each do |user_subscription| %>
          <div class="subscription-item-dash" style="border: 1px solid <%= user_subscription.subscription.category.colour %>; border-left: 8px solid <%= user_subscription.subscription.category.colour %>;">

            <div class="sub-item-overlay">
              <%=link_to user_subscription_path(user_subscription) do %>
                <i class="fas fa-info"></i>
              <% end %>

              <%= link_to edit_user_subscription_path(user_subscription) do %>
                <i class="fas fa-edit"></i>
              <% end %>

              <%= link_to user_subscription_path(user_subscription), method: :delete, data: { confirm: "Are you sure you want to delete this subscription?" } do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            </div>

            <% if user_subscription.subscription.logo_url.nil? %>
              <div class="sub-logo-dash">
                <img src="https://res.cloudinary.com/dkyy/image/upload/v1598968617/Logos/scriber_pe33n6.png" alt="" style="width: 70px; height: 70px;">
              </div>
            <% else %>
              <div class="sub-logo-dash">
                <img src="<%= user_subscription.subscription.logo_url %>" alt="" style="width: 70px; height: 70px;">
              </div>
            <% end %>

            <div class="sub-info-dash">
              <h3 class="sub-name-dash"><%= user_subscription.subscription.name %></h3>
              <p class='sub-next-payment-dash'>Next payment: <%= user_subscription.payment_date %></p>
            </div>

            <div class="sub-reg-cost-dash">
              <h3>£<%= number_with_precision(user_subscription.cost, precision: 2) %></h3>
              <% if user_subscription.reminders.length > 0 %>
                <p class="m-0" id="setAlert">🔔</p>
              <% end %>
            </div>
          </div>
        <% end %>
        <h5 class="text-right mt-3 mr-2"><strong>Total:</strong> £<%=@total_cost %></h5>
      </div>
    </div>
  </div>
</div>

app/views/pages/_dash_tab_profile.html.erb
<div class="row justify-content-center">
  <div class="col-12 col-lg-6">
    <h2 class="text-center mb-3">Profile</h2>
    <div class="profilepage">
      <h3><i class="far fa-user-circle"></i> <%= (current_user.first_name).capitalize =%> <%= (current_user.last_name).capitalize =%></h3>
      <p><%= current_user.email %></p>
      <%=link_to 'Edit Info', edit_user_registration_path, class: ' edit-profile btn btn-primary' %>
      <%= render "dash_pie", user_reminders: @user_reminders %>
    </div>
  </div>
</div>

app/views/pages/_dash_tab_reminders.html.erb
<div class="row justify-content-center">
  <div class="col-12 col-lg-8">
    <h2 class="text-center mb-3">Reminders</h2>
    <% user_reminders.each do |reminder| %>
      <div class="reminder-name">
        <%=reminder.user_subscription.subscription.name %>
      </div>
      <div class="reminder-item">
        <p><i id="bell" class="far fa-bell"></i><%= reminder.date %>:  <%= reminder.details %> </p>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/admin.html.erb
<%= link_to "SEND REMINDERS", send_reminders_path, method: :post, class: "btn btn-lg btn-danger" %>

app/views/pages/dashboard.html.erb
<div class="dash-container">

  <div class="d-flex justify-content-between align-items-center mt-3 mb-4">
    <h1 class="text-left m-0">Dashboard</h1>
    <div>
        <% if @date_match %>
        <div class="flash-alert flash-danger alert-item alert-dismissible fade show" role="alert" id="date-today-alert">
          <span class="mr-3">You have <strong><%= @date_today_count %></strong> <%= @date_today_count > 1 ? 'reminders' : 'reminder' %> today 😱</span>
          <a data-dismiss="alert" aria-label="Close">
          <i id="close-alert" class="fas fa-times"></i>
          </a>
        </div>
      <% else %>
        <div class="flash-alert flash-danger alert-item alert-dismissible fade show" role="alert" id="date-today-alert">
          <span class="mr-3"> You have no reminders today! 🎉 </span>
          <a data-dismiss="alert" aria-label="Close">
          <i id="close-alert" class="fas fa-times"></i>
          </a>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row justify-content-center">

    <div class="col-12 col-lg-3" id="tabs-container">
      <div class="nav flex-column nav-pills tabs-section-buttons" id="v-pills-tab" role="tablist" aria-orientation="vertical">
        <a class="nav-link active" id="v-pills-current-tab" data-toggle="pill" href="#v-pills-current" role="tab" aria-controls="v-pills-current" aria-selected="true"><i class="far fa-calendar-check"></i>Current subscriptions</a>
        <a class="nav-link" id="v-pills-all-tab" data-toggle="pill" href="#v-pills-all" role="tab" aria-controls="v-pills-all" aria-selected="false"><i class="fas fa-search-dollar"></i>All subscriptions</a>
        <a class="nav-link" id="v-pills-reminders-tab" data-toggle="pill" href="#v-pills-reminders" role="tab" aria-controls="v-pills-reminders" aria-selected="false"><i id="reminders-tab" class="far fa-bell"></i> Reminders</a>
        <a class="nav-link" id="v-pills-profile-tab" data-toggle="pill" href="#v-pills-profile" role="tab" aria-controls="v-pills-profile" aria-selected="false"><i class="far fa-user-circle"></i>Profile</a>
      </div>
    </div>

    <div class="col-12 col-lg-9">
      <div class="tab-content" id="v-pills-tabContent">

        <div class="tab-pane fade show active" id="v-pills-current" role="tabpanel" aria-labelledby="v-pills-current-tab" style="height: 100%;">
          <%= render "dash_tab_current", user_subscriptions: @user_subscriptions, subscriptions_current_month: @subscriptions_current_month %>
        </div>

        <div class="tab-pane fade" id="v-pills-all" role="tabpanel" aria-labelledby="v-pills-all-tab">
          <%= render "dash_tab_all", search_results: @search_results %>
        </div>

        <div class="tab-pane fade" id="v-pills-reminders" role="tabpanel" aria-labelledby="v-pills-reminders-tab">
          <%= render "dash_tab_reminders", user_reminders: @user_reminders %>
        </div>

        <div class="tab-pane fade" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">
          <%= render "dash_tab_profile" %>
        </div>

      </div>
    </div>
  </div>
</div>


<script type="text/javascript">
   $(document).on("turbolinks:load", function () {
    const alertToday = document.getElementById('date-today-alert');
    const closeAlert = document.getElementById('close-alert');
    const reminderBell =document.getElementById('reminders-tab');

    closeAlert.addEventListener('click', ()=> {
      alertToday.style.visibility="hidden";
    })
    alertToday.addEventListener('mouseenter', () => {
      reminderBell.classList.add('bellshakeclass')
    })
    alertToday.addEventListener('mouseleave', () => {
      reminderBell.classList.remove('bellshakeclass')
    })
  });
</script>

app/views/reminders/_reminder_form.html.erb
<%= simple_form_for ([user_subscription, reminder]) do |f| %>
  <%= f.input :date, as: :date, html5: true %>
  <%= f.input :details %>
  <div class="text-right">
    <%= link_to "Cancel", :back, class: "btn btn-outline-secondary" %>
    <%= f.button :submit, "Submit", class: "btn btn-primary ml-2" %>
  </div>
<% end %>

app/views/reminders/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <div class="list-subscription-container">
        <h2 class="text-center">Edit reminder</h2>
        <%= render "reminder_form", user_subscription: @user_subscription, reminder: @reminder %>
      </div>
    </div>
  </div>
</div>

app/views/reminders/index.html.erb
<div class="container">
  <div class ="form-container">
    <div class="row justify-content-center">
      <div class="col-8">
        <div class="list-subscription-container">

<h1> <%= @user_subscription.subscription.name %></h1>
<h5> Your Reminder details:</h5>
<% @user_subscription.reminders.each do |reminder|%>
 <div class="reminder-index-item">
   <p> <%= reminder.details %> </p>
   <p> <%= reminder.date %>
 </div>
<% end %>
</div>
      </div>
    </div>
  </div>
</div>

app/views/reminders/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <div class="list-subscription-container">
        <h2 class="text-center">Add reminder</h2>
        <%= render "reminder_form", user_subscription: @user_subscription, reminder: @reminder %>
      </div>
    </div>
  </div>
</div>

app/views/user_subscriptions/show.html.erb
<% content_for :meta_title, "#{@user_subscription.subscription.name} - #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @user_subscription.subscription.description %>
<div class="container">
  <div class="list-subscription-container">
    <div class="show-header">
      <h1><%=@user_subscription.subscription.name%></h1>
      <div>
        <%= link_to user_subscription_path(@user_subscription), method: :delete, data: { confirm: "Are you sure you want to delete this subscription?" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
        <%= link_to edit_user_subscription_path(@user_subscription) do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>
    </div>


    <div class="d-flex justify-content-start">
      <div class="subscription-logo pl-5">
        <% if @user_subscription.subscription.logo_url.nil? %>
          <img src="https://res.cloudinary.com/dkyy/image/upload/v1598968617/Logos/scriber_pe33n6.png" alt="">
        <% else %>
          <img src="<%= @user_subscription.subscription.logo_url %>" alt="">
        <% end %>
      </div>

      <div class="pl-5">
        <p><b>Subscription details:</b> <i><%= @user_subscription.subscription.description %></i></p>
        <p><strong>Start date:</strong> <%= @user_subscription.start_date %></p>
        <p><strong>End date: </strong><%= @user_subscription.end_date %></p>
        <p><strong>Payment date: </strong><%= @user_subscription.payment_date %></p>
        <p><strong>Billing plan:</strong> <%= @user_subscription.billing_plan.name %></p>
        <p><strong>Cost:</strong> £<%= number_with_precision(@user_subscription.cost, precision: 2) %></p>
        <div class="d-flex"><p><strong>Category: </strong></p><p class="ml-1" style="color: <%= @user_subscription.subscription.category.colour %>;"><%= @user_subscription.subscription.category.name %></p></div>
      </div>
    </div>

    <% if @user_subscription.reminders.count > 0 %>
      <div class= "reminders-box m-3">
        <div class="d-flex justify-content-between align-items-center mb-3">
          <h4 class="font-weight-bold">Reminders</h4>
          <div class="add-reminder-btn">
            <%= link_to new_user_subscription_reminder_path(@user_subscription) do %>
              Add reminder <i class="fas fa-plus ml-1"></i>
            <% end %>
          </div>
        </div>
        <% @user_subscription.reminders.each do |reminder|%>
          <div class="reminder-box-item">
            <p class="p-2 m-0">🔔  <strong><%= reminder.date %>:</strong> <%= reminder.details %></p>
            <div class="reminder-box-icons">
              <%= link_to reminder_path(reminder), method: :delete, data: { confirm: "Are you sure you want to delete this reminder?" } do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
              <%= link_to edit_user_subscription_reminder_path(@user_subscription, reminder) do %>
                <i class="fas fa-edit"></i>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    <% else %>
      <div class="add-reminder-btn ml-5">
        <%= link_to new_user_subscription_reminder_path(@user_subscription) do %>
          Add reminder <i class="fas fa-plus ml-1"></i>
        <% end %>
      </div>
    <% end %>

    <div class="mr-3 text-right">
      <%= link_to "Back", dashboard_path, class: 'btn btn-outline-secondary btn-sm ml-2' %>
    </div>
  </div>
</div>